### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by tomalrussell** [tud-hri/travia#1]
Hi @OlgerSiebinga, I'm just starting a review for your JOSS paper (https://github.com/openjournals/joss-reviews/issues/3607).

Could you move or copy the GPL license in `COPYING` to `LICENSE.txt`, to check off one of the points on the review checklist?

**Comment by OlgerSiebinga** [comment]
Hi @tomalrussell, Thanks for taking the time to review my paper!

I thought a `COPYING` file was the standard for a GPL license, and also [acceptable for JOSS](https://joss.readthedocs.io/en/latest/review_criteria.html#software-license). But if you don't agree I'll change it, no problem.

**Comment by tomalrussell** [comment]
Ah no, that's fine - I'm more familiar with seeing `LICENSE` is all,  and this is the first time I'm reviewing for JOSS so wanted to dot the i's and cross the t's 🙂
