### ISSUE TITLE
How to get the data (in .csv) after smoothing

### ISSUE THREAD

**Issue by EurekaC-43** [tud-hri/travia#12]
hi!
I used travia to visualize data in pNEUMA and it works very well! Now I‘m trying to get the dataframe after loading and smoothing just like the screenshot below, but I don't know how to get it. Can I ask for some help?
![image](https://github.com/tud-hri/travia/assets/123283828/ef5bbaac-b3ce-46fd-acde-3b2384c23eee)

**Comment by OlgerSiebinga** [comment]
Hi @EurekaC-43,

You can save the data to a `*.csv` file using the [`to_csv`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html) method from pandas. The trajectory data can be found in a data frame in the `PNeumaDataset` called `track_data`. So just call `data.track_data.to_csv(PATH)` after loading the data (e.g., at the end of the visualize script). Hope this helps!

**Comment by EurekaC-43** [comment]
Thanks! It works!
