### ISSUE TITLE
pNeuma image offset

### ISSUE THREAD

**Issue by tomalrussell** [tud-hri/travia#8]
The TIFF provided in the repository is not aligned with the tracks data from pNeuma `D181030_T0930_1000_DR1`, so the vehicles show up on a grey background outside of the image area. 

Should I test with a different pNeuma dataset, or another image?

See screenshot:

![offset background](https://user-images.githubusercontent.com/2762769/133996722-cc53d19c-23b5-421d-b33a-e65a31c82e97.png)

**Comment by OlgerSiebinga** [comment]
I suspect that the map is aligned, just not big enough for this particular part of the dataset. I'll look into it and see if a bigger map fixes the issue.

**Comment by OlgerSiebinga** [comment]
This was the case, I've added a bigger background image in commit 47549ef
